import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/global/Header";
import Footer from "@/components/global/Footer";

// Replace GeistSans and GeistMono with Grifter font
const grifterFont = localFont({
  src: "./fonts/grifterbold.otf", // Replace with the actual path to your Grifter font
  variable: "--font-grifter",
  weight: "100 900", // Adjust weight range if necessary
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${grifterFont.variable} antialiased bg-[#F9F9F9]`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
